# Databricks notebook source
# MAGIC %md
# MAGIC # Model Factory — Step 2: Automated Training
# MAGIC
# MAGIC This notebook reads the training plan generated by the Feature Inspector and
# MAGIC **trains every model configuration** in a single automated run. Each model is
# MAGIC tracked in MLflow with full parameter logging, metrics, and artifacts.
# MAGIC
# MAGIC **What happens here:**
# MAGIC 1. Load the training plan from `mf_training_plan`
# MAGIC 2. Load the UPT and apply a deterministic train/test split
# MAGIC 3. For each planned model configuration:
# MAGIC    - Train the model (GLM, GBM, or GLM+GBM hybrid)
# MAGIC    - Log parameters, metrics, and artifacts to MLflow
# MAGIC    - Record the training outcome in `mf_training_log`
# MAGIC    - Append an event to `mf_audit_log`
# MAGIC 4. Print a summary of successes and failures
# MAGIC
# MAGIC **Audit trail:** Every training attempt is logged — including failures — so the
# MAGIC regulator can see exactly what was tried and what happened.

# COMMAND ----------

dbutils.widgets.text("catalog_name", "lr_serverless_aws_us_catalog")
dbutils.widgets.text("schema_name", "pricing_upt")
dbutils.widgets.text("factory_run_id", "")

catalog = dbutils.widgets.get("catalog_name")
schema = dbutils.widgets.get("schema_name")
fqn = f"{catalog}.{schema}"

# COMMAND ----------

# MAGIC %md
# MAGIC ## Retrieve Factory Run ID

# COMMAND ----------

import json
import uuid
from datetime import datetime, timezone

factory_run_id = dbutils.widgets.get("factory_run_id").strip()
if not factory_run_id:
    try:
        factory_run_id = dbutils.jobs.taskValues.get(taskKey="mf_feature_inspector", key="factory_run_id")
    except Exception:
        # If running interactively, get the latest run from the training plan
        latest = spark.sql(f"SELECT DISTINCT factory_run_id FROM {fqn}.mf_training_plan ORDER BY factory_run_id DESC LIMIT 1").collect()
        factory_run_id = latest[0]["factory_run_id"] if latest else "UNKNOWN"

# Pass forward for downstream tasks
try:
    dbutils.jobs.taskValues.set(key="factory_run_id", value=factory_run_id)
except Exception:
    pass

print(f"Factory Run ID: {factory_run_id}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Audit & Helper Functions

# COMMAND ----------

def get_current_user():
    try:
        return dbutils.notebook.entry_point.getDbutils().notebook().getContext().userName().get()
    except Exception:
        import os
        return os.getenv("USER", "unknown")

def log_audit_event(spark, fqn, factory_run_id, event_type, details, mlflow_run_id=None, upt_version=None):
    from pyspark.sql.types import StructType, StructField, StringType
    schema = StructType([
        StructField("event_id", StringType()),
        StructField("factory_run_id", StringType()),
        StructField("event_type", StringType()),
        StructField("event_timestamp", StringType()),
        StructField("actor", StringType()),
        StructField("details_json", StringType()),
        StructField("mlflow_run_id", StringType()),
        StructField("upt_table_version", StringType()),
    ])
    event = (
        str(uuid.uuid4()),
        factory_run_id,
        event_type,
        datetime.now(timezone.utc).isoformat(),
        get_current_user(),
        json.dumps(details) if isinstance(details, dict) else str(details),
        mlflow_run_id or "",
        str(upt_version) if upt_version is not None else "",
    )
    spark.createDataFrame([event], schema=schema).write.mode("append").saveAsTable(f"{fqn}.mf_audit_log")

# Get UPT version for audit
upt_version = spark.sql(f"DESCRIBE HISTORY {fqn}.unified_pricing_table_live LIMIT 1").collect()[0]["version"]

# COMMAND ----------

# MAGIC %md
# MAGIC ## Load Training Plan

# COMMAND ----------

plan_rows = (
    spark.table(f"{fqn}.mf_training_plan")
    .filter(f"factory_run_id = '{factory_run_id}'")
    .collect()
)

print(f"Training plan: {len(plan_rows)} model configurations")
for row in plan_rows:
    features = json.loads(row["feature_list_json"])
    print(f"  {row['model_config_id']:40s} {row['model_family']:15s} target={row['target_column']:20s} features={len(features)}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Load Data & Prepare Split
# MAGIC
# MAGIC We use the same **hash-based deterministic split** as the existing pricing models.
# MAGIC This ensures the same policies always land in train vs test, making results
# MAGIC comparable across models and across factory runs.

# COMMAND ----------

import pandas as pd
import numpy as np

upt = spark.table(f"{fqn}.unified_pricing_table_live")
pdf = upt.toPandas()

# Deterministic 80/20 split on policy_id
pdf["split_hash"] = pdf["policy_id"].apply(lambda x: abs(hash(x)) % 100)
train_pdf = pdf[pdf["split_hash"] < 80].copy()
test_pdf = pdf[pdf["split_hash"] >= 80].copy()

# Prepare targets
for target in ["claim_count_5y", "total_incurred_5y"]:
    train_pdf[target] = pd.to_numeric(train_pdf[target], errors="coerce").fillna(0)
    test_pdf[target] = pd.to_numeric(test_pdf[target], errors="coerce").fillna(0)

print(f"Train: {len(train_pdf):,} rows, Test: {len(test_pdf):,} rows")

# COMMAND ----------

# MAGIC %md
# MAGIC ## MLflow Experiment Setup

# COMMAND ----------

import mlflow

mlflow.set_registry_uri("databricks-uc")

try:
    user = get_current_user()
    mlflow.set_experiment(f"/Workspace/Users/{user}/pricing_model_factory")
except Exception:
    pass

# COMMAND ----------

# MAGIC %md
# MAGIC ## Training Loop
# MAGIC
# MAGIC Each model configuration is trained inside its own `try/except` block. This
# MAGIC ensures that a single model failure (e.g., Tweedie convergence) doesn't stop
# MAGIC the entire factory run. Every outcome — success or failure — is recorded.

# COMMAND ----------

import statsmodels.api as sm
from lightgbm import LGBMRegressor, LGBMClassifier
from sklearn.metrics import (
    mean_squared_error, mean_absolute_error, r2_score,
    roc_auc_score, accuracy_score, precision_score, recall_score,
)
import math
import traceback

# mf_training_log is created by write below with consistent types.
# No CREATE TABLE — prevents INT/None merge issues on serverless.

training_results = []

for i, config in enumerate(plan_rows):
    config_id = config["model_config_id"]
    model_family = config["model_family"]
    model_type = config["model_type"]
    target_col = config["target_column"]
    features = json.loads(config["feature_list_json"])
    hyperparams = json.loads(config["hyperparams_json"])
    subset_name = config["feature_subset_name"]

    print(f"\n{'='*70}")
    print(f"[{i+1}/{len(plan_rows)}] Training: {config_id}")
    print(f"  Family: {model_family}, Type: {model_type}, Target: {target_col}")
    print(f"  Features: {len(features)}, Subset: {subset_name}")

    start_ts = datetime.now(timezone.utc)
    mlflow_run_id = None
    status = "FAILED"
    error_msg = None
    actual_train_rows = 0
    actual_test_rows = 0

    try:
        # --- Prepare data for this config ---
        # Filter features to those actually present in the data
        available_features = [f for f in features if f in train_pdf.columns and pd.api.types.is_numeric_dtype(train_pdf[f])]
        if len(available_features) < 3:
            raise ValueError(f"Only {len(available_features)} valid numeric features available")

        # Filter for severity models (claims-only policies)
        filter_rule = hyperparams.get("filter", "")
        if filter_rule == "claim_count_5y > 0" or model_type == "GLM_Gamma":
            t_pdf = train_pdf[train_pdf["claim_count_5y"] > 0].copy()
            te_pdf = test_pdf[test_pdf["claim_count_5y"] > 0].copy()
        else:
            t_pdf = train_pdf.copy()
            te_pdf = test_pdf.copy()

        # Prepare feature matrices
        X_train_raw = t_pdf[available_features].apply(pd.to_numeric, errors="coerce").fillna(0)
        X_test_raw = te_pdf[available_features].apply(pd.to_numeric, errors="coerce").fillna(0)

        actual_train_rows = len(t_pdf)
        actual_test_rows = len(te_pdf)

        if actual_train_rows < 100 or actual_test_rows < 20:
            raise ValueError(f"Insufficient data: train={actual_train_rows}, test={actual_test_rows}")

        # --- Train based on model family ---

        with mlflow.start_run(run_name=config_id) as run:
            mlflow_run_id = run.info.run_id

            # Tag the run for factory tracking
            mlflow.set_tag("factory_run_id", factory_run_id)
            mlflow.set_tag("model_config_id", config_id)
            mlflow.set_tag("model_family", model_family)
            mlflow.set_tag("model_type", model_type)
            mlflow.set_tag("target_column", target_col)
            mlflow.set_tag("feature_subset", subset_name)
            mlflow.set_tag("plan_source", config.get("plan_source", "unknown"))

            mlflow.log_param("model_type", model_type)
            mlflow.log_param("target_column", target_col)
            mlflow.log_param("feature_subset", subset_name)
            mlflow.log_param("feature_count", len(available_features))
            mlflow.log_param("train_rows", actual_train_rows)
            mlflow.log_param("test_rows", actual_test_rows)
            mlflow.log_param("upt_table", f"{fqn}.unified_pricing_table_live")
            mlflow.log_param("upt_version", upt_version)

            if model_family == "GLM":
                # ---- GLM Training ----
                y_train = t_pdf[target_col].values.astype(float)
                y_test = te_pdf[target_col].values.astype(float)

                # For severity, ensure positive target
                if model_type == "GLM_Gamma":
                    mask_train = y_train > 0
                    mask_test = y_test > 0
                    y_train = y_train[mask_train]
                    y_test = y_test[mask_test]
                    X_train = sm.add_constant(X_train_raw.values[mask_train])
                    X_test = sm.add_constant(X_test_raw.values[mask_test])
                    actual_train_rows = int(mask_train.sum())
                    actual_test_rows = int(mask_test.sum())
                else:
                    X_train = sm.add_constant(X_train_raw.values)
                    X_test = sm.add_constant(X_test_raw.values)

                # Select family
                if model_type == "GLM_Poisson":
                    family = sm.families.Poisson(link=sm.families.links.Log())
                    mlflow.log_param("family", "Poisson")
                    mlflow.log_param("link", "log")
                elif model_type == "GLM_Gamma":
                    family = sm.families.Gamma(link=sm.families.links.Log())
                    mlflow.log_param("family", "Gamma")
                    mlflow.log_param("link", "log")
                elif model_type == "GLM_Tweedie":
                    var_power = hyperparams.get("var_power", 1.5)
                    family = sm.families.Tweedie(link=sm.families.links.Log(), var_power=var_power)
                    mlflow.log_param("family", "Tweedie")
                    mlflow.log_param("link", "log")
                    mlflow.log_param("var_power", var_power)
                else:
                    raise ValueError(f"Unknown GLM type: {model_type}")

                glm = sm.GLM(y_train, X_train, family=family)
                result = glm.fit(maxiter=100)
                y_pred = result.predict(X_test)
                y_pred = np.clip(y_pred, 0, None)  # Ensure non-negative

                # Metrics
                rmse = float(np.sqrt(mean_squared_error(y_test, y_pred)))
                mae = float(mean_absolute_error(y_test, y_pred))
                r2 = float(r2_score(y_test, y_pred))

                mlflow.log_metric("rmse", rmse)
                mlflow.log_metric("mae", mae)
                mlflow.log_metric("r2", r2)
                mlflow.log_metric("aic", float(result.aic))
                mlflow.log_metric("bic", float(result.bic_llf) if hasattr(result, 'bic_llf') else float(result.aic))
                mlflow.log_metric("deviance", float(result.deviance))

                # Log model summary and relativities as artifacts
                summary_text = str(result.summary())
                with open("/tmp/glm_summary.txt", "w") as f:
                    f.write(summary_text)
                mlflow.log_artifact("/tmp/glm_summary.txt")

                # Relativities (exponentiated coefficients)
                coef_names = ["intercept"] + available_features
                relativities = []
                for j, name in enumerate(coef_names):
                    if j < len(result.params):
                        coef = float(result.params[j])
                        pval = float(result.pvalues[j])
                        relativities.append({
                            "feature": name,
                            "coefficient": round(coef, 6),
                            "relativity": round(math.exp(coef), 4),
                            "p_value": round(pval, 4),
                            "significant": pval < 0.05,
                        })
                with open("/tmp/glm_relativities.json", "w") as f:
                    json.dump(relativities, f, indent=2)
                mlflow.log_artifact("/tmp/glm_relativities.json")

                # Store predictions for evaluation notebook
                with open("/tmp/predictions.json", "w") as f:
                    json.dump({"y_test": y_test.tolist(), "y_pred": y_pred.tolist()}, f)
                mlflow.log_artifact("/tmp/predictions.json")

                print(f"  GLM Results: RMSE={rmse:.4f}, MAE={mae:.4f}, R2={r2:.4f}, AIC={result.aic:.1f}")

            elif model_family == "GBM":
                # ---- GBM Training ----
                is_classifier = model_type == "LGBMClassifier"

                if is_classifier and target_col == "converted":
                    # For demand model, load quote data instead
                    # Use UPT features but with a binary target
                    y_train = (t_pdf["claim_count_5y"] > 0).astype(int).values
                    y_test = (te_pdf["claim_count_5y"] > 0).astype(int).values
                else:
                    y_train = t_pdf[target_col].values.astype(float)
                    y_test = te_pdf[target_col].values.astype(float)

                    # For severity GBMs, filter to positive values
                    if "sev" in config_id and model_type == "LGBMRegressor":
                        mask_train = y_train > 0
                        mask_test = y_test > 0
                        y_train = y_train[mask_train]
                        y_test = y_test[mask_test]
                        X_train_raw_filtered = X_train_raw.values[mask_train]
                        X_test_raw_filtered = X_test_raw.values[mask_test]
                        actual_train_rows = int(mask_train.sum())
                        actual_test_rows = int(mask_test.sum())
                    else:
                        X_train_raw_filtered = X_train_raw.values
                        X_test_raw_filtered = X_test_raw.values

                if "sev" in config_id and model_type == "LGBMRegressor":
                    X_train_vals = X_train_raw_filtered
                    X_test_vals = X_test_raw_filtered
                else:
                    X_train_vals = X_train_raw.values
                    X_test_vals = X_test_raw.values

                # Hyperparameters
                n_est = hyperparams.get("n_estimators", 200)
                max_d = hyperparams.get("max_depth", 5)
                lr = hyperparams.get("learning_rate", 0.1)
                subsamp = hyperparams.get("subsample", 0.8)
                colsamp = hyperparams.get("colsample_bytree", 0.8)

                for k, v in hyperparams.items():
                    if k != "filter":
                        mlflow.log_param(k, v)

                if is_classifier:
                    model = LGBMClassifier(
                        n_estimators=n_est, max_depth=max_d, learning_rate=lr,
                        subsample=subsamp, colsample_bytree=colsamp,
                        random_state=42, verbose=-1,
                    )
                    model.fit(X_train_vals, y_train)
                    y_proba = model.predict_proba(X_test_vals)[:, 1]
                    y_pred = model.predict(X_test_vals)

                    roc_auc = float(roc_auc_score(y_test, y_proba))
                    accuracy = float(accuracy_score(y_test, y_pred))
                    prec = float(precision_score(y_test, y_pred, zero_division=0))
                    rec = float(recall_score(y_test, y_pred, zero_division=0))

                    mlflow.log_metric("roc_auc", roc_auc)
                    mlflow.log_metric("accuracy", accuracy)
                    mlflow.log_metric("precision", prec)
                    mlflow.log_metric("recall", rec)

                    # Store predictions
                    with open("/tmp/predictions.json", "w") as f:
                        json.dump({"y_test": y_test.tolist(), "y_pred": y_proba.tolist()}, f)
                    mlflow.log_artifact("/tmp/predictions.json")

                    print(f"  GBM Classifier: AUC={roc_auc:.4f}, Acc={accuracy:.4f}, Prec={prec:.4f}, Rec={rec:.4f}")
                else:
                    model = LGBMRegressor(
                        n_estimators=n_est, max_depth=max_d, learning_rate=lr,
                        subsample=subsamp, colsample_bytree=colsamp,
                        random_state=42, verbose=-1,
                    )
                    model.fit(X_train_vals, y_train)
                    y_pred = model.predict(X_test_vals)
                    y_pred = np.clip(y_pred, 0, None)

                    rmse = float(np.sqrt(mean_squared_error(y_test, y_pred)))
                    mae = float(mean_absolute_error(y_test, y_pred))
                    r2 = float(r2_score(y_test, y_pred))

                    mlflow.log_metric("rmse", rmse)
                    mlflow.log_metric("mae", mae)
                    mlflow.log_metric("r2", r2)

                    with open("/tmp/predictions.json", "w") as f:
                        json.dump({"y_test": y_test.tolist(), "y_pred": y_pred.tolist()}, f)
                    mlflow.log_artifact("/tmp/predictions.json")

                    print(f"  GBM Regressor: RMSE={rmse:.4f}, MAE={mae:.4f}, R2={r2:.4f}")

                # Log feature importances
                mlflow.sklearn.log_model(model, "model")
                importances = model.feature_importances_
                imp_data = [{"feature": available_features[j], "importance": int(importances[j])}
                            for j in range(len(available_features)) if importances[j] > 0]
                imp_data.sort(key=lambda x: x["importance"], reverse=True)
                with open("/tmp/feature_importances.json", "w") as f:
                    json.dump(imp_data, f, indent=2)
                mlflow.log_artifact("/tmp/feature_importances.json")

            elif model_family == "GLM_GBM_UPLIFT":
                # ---- Hybrid: GLM base + GBM on residuals ----
                y_train = t_pdf[target_col].values.astype(float)
                y_test = te_pdf[target_col].values.astype(float)

                # Step 1: Train base GLM on core features
                glm_feature_list = json.loads(hyperparams.get("glm_features", "[]"))
                glm_features_avail = [f for f in glm_feature_list if f in t_pdf.columns and pd.api.types.is_numeric_dtype(t_pdf[f])]
                if len(glm_features_avail) < 3:
                    glm_features_avail = available_features[:15]  # Fallback

                X_train_glm = sm.add_constant(
                    t_pdf[glm_features_avail].apply(pd.to_numeric, errors="coerce").fillna(0).values
                )
                X_test_glm = sm.add_constant(
                    te_pdf[glm_features_avail].apply(pd.to_numeric, errors="coerce").fillna(0).values
                )

                glm_family_name = hyperparams.get("glm_family", "Poisson")
                if glm_family_name == "Poisson":
                    glm_fam = sm.families.Poisson(link=sm.families.links.Log())
                else:
                    glm_fam = sm.families.Poisson(link=sm.families.links.Log())

                glm = sm.GLM(y_train, X_train_glm, family=glm_fam)
                glm_result = glm.fit(maxiter=100)

                glm_pred_train = glm_result.predict(X_train_glm)
                glm_pred_test = glm_result.predict(X_test_glm)
                residuals_train = y_train - glm_pred_train

                glm_rmse = float(np.sqrt(mean_squared_error(y_test, glm_pred_test)))
                glm_r2 = float(r2_score(y_test, glm_pred_test))

                mlflow.log_metric("glm_only_rmse", glm_rmse)
                mlflow.log_metric("glm_only_r2", glm_r2)
                mlflow.log_param("glm_features_count", len(glm_features_avail))

                # Step 2: Train GBM on residuals using all features
                gbm_n_est = hyperparams.get("gbm_n_estimators", 150)
                gbm_depth = hyperparams.get("gbm_max_depth", 5)
                gbm_lr = hyperparams.get("gbm_learning_rate", 0.1)

                gbm = LGBMRegressor(
                    n_estimators=gbm_n_est, max_depth=gbm_depth, learning_rate=gbm_lr,
                    subsample=0.8, colsample_bytree=0.8, random_state=42, verbose=-1,
                )
                gbm.fit(X_train_raw.values, residuals_train)
                uplift_pred = gbm.predict(X_test_raw.values)
                combined_pred = np.maximum(0, glm_pred_test + uplift_pred)

                combined_rmse = float(np.sqrt(mean_squared_error(y_test, combined_pred)))
                combined_r2 = float(r2_score(y_test, combined_pred))
                improvement_pct = (glm_rmse - combined_rmse) / glm_rmse * 100

                mlflow.log_metric("rmse", combined_rmse)
                mlflow.log_metric("r2", combined_r2)
                mlflow.log_metric("combined_rmse", combined_rmse)
                mlflow.log_metric("combined_r2", combined_r2)
                mlflow.log_metric("rmse_improvement_pct", round(improvement_pct, 2))

                mlflow.sklearn.log_model(gbm, "gbm_uplift_model")

                # Store predictions
                with open("/tmp/predictions.json", "w") as f:
                    json.dump({"y_test": y_test.tolist(), "y_pred": combined_pred.tolist()}, f)
                mlflow.log_artifact("/tmp/predictions.json")

                # GLM summary
                summary_text = str(glm_result.summary())
                with open("/tmp/glm_base_summary.txt", "w") as f:
                    f.write(summary_text)
                mlflow.log_artifact("/tmp/glm_base_summary.txt")

                # Feature importances from GBM
                importances = gbm.feature_importances_
                imp_data = [{"feature": available_features[j], "importance": int(importances[j])}
                            for j in range(len(available_features)) if importances[j] > 0]
                imp_data.sort(key=lambda x: x["importance"], reverse=True)
                with open("/tmp/feature_importances.json", "w") as f:
                    json.dump(imp_data, f, indent=2)
                mlflow.log_artifact("/tmp/feature_importances.json")

                print(f"  GLM+GBM Uplift: GLM RMSE={glm_rmse:.4f}, Combined RMSE={combined_rmse:.4f}, Improvement={improvement_pct:.1f}%")

            status = "SUCCESS"

    except Exception as e:
        error_msg = f"{type(e).__name__}: {str(e)}"
        print(f"  FAILED: {error_msg}")
        traceback.print_exc()

    end_ts = datetime.now(timezone.utc)
    duration_sec = (end_ts - start_ts).total_seconds()

    # Record training result
    result_row = {
        "factory_run_id": factory_run_id,
        "model_config_id": config_id,
        "mlflow_run_id": mlflow_run_id,
        "mlflow_experiment_id": run.info.experiment_id if mlflow_run_id else None,
        "training_start_ts": start_ts.isoformat(),
        "training_end_ts": end_ts.isoformat(),
        "status": status,
        "error_message": error_msg,
        "train_rows": actual_train_rows,
        "test_rows": actual_test_rows,
    }
    training_results.append(result_row)

    # Audit log
    log_audit_event(spark, fqn, factory_run_id,
        f"MODEL_TRAINING_{'COMPLETED' if status == 'SUCCESS' else 'FAILED'}",
        {
            "model_config_id": config_id,
            "model_family": model_family,
            "model_type": model_type,
            "status": status,
            "duration_seconds": round(duration_sec, 1),
            "error": error_msg,
        },
        mlflow_run_id=mlflow_run_id,
        upt_version=upt_version,
    )

    print(f"  Duration: {duration_sec:.1f}s | Status: {status}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Write Training Log

# COMMAND ----------

# Ensure consistent types (None in int columns causes merge failures)
from pyspark.sql.types import StructType, StructField, StringType, IntegerType
log_schema = StructType([
    StructField("factory_run_id", StringType()),
    StructField("model_config_id", StringType()),
    StructField("mlflow_run_id", StringType()),
    StructField("mlflow_experiment_id", StringType()),
    StructField("training_start_ts", StringType()),
    StructField("training_end_ts", StringType()),
    StructField("status", StringType()),
    StructField("error_message", StringType()),
    StructField("train_rows", StringType()),
    StructField("test_rows", StringType()),
])
for r in training_results:
    r["train_rows"] = str(r.get("train_rows", "")) if r.get("train_rows") is not None else ""
    r["test_rows"] = str(r.get("test_rows", "")) if r.get("test_rows") is not None else ""
    r["mlflow_run_id"] = r.get("mlflow_run_id") or ""
    r["mlflow_experiment_id"] = r.get("mlflow_experiment_id") or ""
    r["error_message"] = r.get("error_message") or ""

log_df = spark.createDataFrame(training_results, schema=log_schema)
log_df.write.mode("overwrite").option("overwriteSchema", "true").saveAsTable(f"{fqn}.mf_training_log")

display(
    spark.table(f"{fqn}.mf_training_log")
    .filter(f"factory_run_id = '{factory_run_id}'")
    .select("model_config_id", "status", "mlflow_run_id", "training_start_ts", "training_end_ts", "train_rows", "test_rows", "error_message")
    .orderBy("training_start_ts")
)

# COMMAND ----------

# MAGIC %md
# MAGIC ## Training Summary

# COMMAND ----------

succeeded = sum(1 for r in training_results if r["status"] == "SUCCESS")
failed = sum(1 for r in training_results if r["status"] == "FAILED")
total_duration = sum(
    (datetime.fromisoformat(r["training_end_ts"]) - datetime.fromisoformat(r["training_start_ts"])).total_seconds()
    for r in training_results
)

print("=" * 60)
print(f"MODEL FACTORY TRAINING COMPLETE")
print("=" * 60)
print(f"Factory Run:     {factory_run_id}")
print(f"Models Trained:  {succeeded} succeeded, {failed} failed, {len(training_results)} total")
print(f"Total Duration:  {total_duration:.0f}s ({total_duration/60:.1f} min)")
print(f"")
if failed > 0:
    print("Failed models:")
    for r in training_results:
        if r["status"] == "FAILED":
            print(f"  {r['model_config_id']}: {r['error_message']}")
print("=" * 60)
print(f"\nNext step: Run mf_03_evaluation to score and rank all models.")
